### PR TITLE
 - fixing the bug, when multiple comma-separated patterns were not ap…

### PR DESCRIPTION
**Pull request by sergiy-kozak**
…plied while being set in 'Jobs to show' text field in configuration UI. Fixes issue #72

### CODE REVIEW

**Comment by sergiy-kozak** [comment]
Hi,
I added some more unit tests to cover more situations with filtering by job names, and committed those within this pull request.

**Comment by philipphoffmann** [comment]
cool thx, i will check this

**Comment by sergiy-kozak** [comment]
Hi Philipp,
have you had chance to look into the PR I submitted?

**Comment by philipphoffmann** [comment]
LGTM
sorry for the delay
+1 for the extensive tests :)

**Comment by henricook** [comment]
@philipphoffmann Sorry to bother you with this, but it looks like there's no filter field any more? Only the "jobs to show" box? And that seems to take pipe separated arguments (|) that can't be negated, is that right?

**Comment by philipphoffmann** [comment]
@henricook the way the field works is, you can specify multiple patterns (separated by comma) for matching jobs. E.g. "A*,!AB*" will show jobs starting with "A" but not jobs starting with "AB".
Let me know if that worked for you.

**Comment by henricook** [comment]
That's what i saw in the readme, i really don't know where i'm doing wrong. I have a lot of jobs beginning with 'fset' and 'csr' - so i tried the filter string "csr*,fset*" (without quotes) - this doesn't work, i get "no jobs found". Weird though if i put "csr|fset" i get jobs starting with csr and fset - none of the exclude patterns though e.g (!foobar) work which is what i really want.. any idea what that could be? 

Attempting to fix this i pulled the latest from the repo, the checksums on some files from my /home/henri/.local/share/gnome-shell/extensions/jenkins-indicator@philipphoffmann.de/ are:

69c5c00a26569651b94acbd3eb637319  extension.js
ee47d81a0be8c11e7bd55872f6b82ed7  prefs.js
1f0c80ebcbe56099644c66990d7871e1  jenkinsIndicator.js

(included to prove i'm on latest)

Any leads on the source of this behaviour very much appreciated, i'll happily lend some time to helping fix it if you can help me narrow it down

I'm on Ubuntu Gnome 17.04 - i still had this problem in 16.10 but have only just got around to reporting it (now i have a requirement to exclude something, before it wasn't too much of a bother)

**Pull request merged**
